# petkit/eyes.py
"""Cursor-tracking pupils for the sprite cat.

`pupil_offset` is the pure deflection math. `EYES[state]` is a per-frame table
of (left_eye, right_eye) anchor points in 32-space sprite coordinates -- the
eyes drift a few px across the idle frames, so pupils are re-seated each frame.
Regenerate the table with `python tools/calibrate_eyes.py` and paste below."""
import math


def pupil_offset(dx, dy, reach=55.0, max_off=1.4):
    """Offset (ox,oy) in sprite px for a pupil whose eye is `dx,dy` screen px
    from the cursor: points toward the cursor, grows with distance up to
    `reach`, clamped to `max_off` sprite px."""
    d = math.hypot(dx, dy)
    if d < 1e-6:
        return (0.0, 0.0)
    f = min(1.0, d / reach) * max_off / d
    return (dx * f, dy * f)


EYES = {
    # Generated by tools/calibrate_eyes.py against assets/cat/Idle.png (10 frames).
    "idle": [
        ((6, 13), (18, 12)),
        ((6, 13), (18, 12)),
        ((6, 13), (18, 12)),
        ((7, 13), (18, 12)),
        ((7, 13), (18, 12)),
        ((7, 13), (18, 12)),
        ((7, 13), (18, 12)),
        ((6, 13), (18, 12)),
        ((6, 13), (18, 12)),
        ((6, 13), (18, 12)),
    ],
}
